### ISSUE TITLE
Elkarbackup Docker images

### ISSUE THREAD

**Issue by benjaminderei** [elkarbackup/elkarbackup#158]
Hi,

I want to make elkabackup run in a docker container.
Any image ready ?
If not, can you explain me a little bit the important parts of elkarbackup and i will do it !

**Comment by xezpeleta** [comment]
Hi @benjaminderei ,

Sorry but currently we don't have any docker container.

Elkarbackup is mainly a web project based in Symfony PHP framework. Apart from that, the current debian package configures other things like a Cron task, to check and run pending backup jobs; sudo configuration, to be able to run some commands and scripts as root user, etc...

If you want more information, take a look to https://github.com/elkarbackup/elkarbackup-vm code, specially to the Ansible file that automatically installs Elkarbackup and its dependencies into a clean VM (under "provisioning" directory).

Please, let us know if you build the docker image.

Thanks!!

**Comment by benjaminderei** [comment]
Thx for the response i will try to build a image for elkar !

**Comment by benjaminderei** [comment]
I'm retrying today.... but i think i will give up... the try and error game is boring me.

last error:
```
PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'The stream or file "/var/log/elkarbackup/prod.log" could not be opened: failed to open stream: Permission denied' in /usr/share/elkarbackup/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:87\nStack trace:\n#0 /usr/share/elkarbackup/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\\Handler\\StreamHandler->write(Array)\n#1 /usr/share/elkarbackup/vendor/monolog/monolog/src/Monolog/Handler/FingersCrossedHandler.php(112): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)\n#2 /usr/share/elkarbackup/vendor/monolog/monolog/src/Monolog/Logger.php(289): Monolog\\Handler\\FingersCrossedHandler->handle(Array)\n#3 /usr/share/elkarbackup/vendor/monolog/monolog/src/Monolog/Logger.php(467): Monolog\\Logger->addRecord(500, 'Uncaught Except...', Array)\n#4 /usr/share/elkarbackup/vendor/symfony/symfony/src/Symfony/Component/Debug/ErrorHandler.php(560): Monolog\\Logger->log('critical', 'Uncaught Except...', Array)\n#5 [interna in /usr/share/elkarbackup/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 87

[Tue Sep 13 06:58:33.421528 2016] [:error] [pid 501] [client 77.203.255.95:50380] PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'The stream or file "/var/log/elkarbackup/prod.log" could not be opened: failed to open stream: Permission denied' in /usr/share/elkarbackup/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:87\nStack trace:\n#0 /usr/share/elkarbackup/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\\Handler\\StreamHandler->write(Array)\n#1 /usr/share/elkarbackup/vendor/monolog/monolog/src/Monolog/Handler/FingersCrossedHandler.php(112): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)\n#2 /usr/share/elkarbackup/vendor/monolog/monolog/src/Monolog/Logger.php(289): Monolog\\Handler\\FingersCrossedHandler->handle(Array)\n#3 /usr/share/elkarbackup/vendor/monolog/monolog/src/Monolog/Logger.php(467): Monolog\\Logger->addRecord(500, 'Fatal Error: Un...', Array)\n#4 /usr/share/elkarbackup/vendor/symfony/symfony/src/Symfony/Component/Debug/ErrorHandler.php(560): Monolog\\Logger->log('critical', 'Fatal Error: Un...', Array)\n#5 /usr/sha in /usr/share/elkarbackup/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 87
```

**Comment by xezpeleta** [comment]
Hi @benjaminderei it looks a permission issue. If you show me your Dockerfile maybe I can help you.

**Comment by benjaminderei** [comment]
Hello,
I have let my dockerfile this way:
```
FROM debian:jessie

RUN apt-get update
RUN apt-get install -y debconf php5 php5-cli rsnapshot php5-mysql acl bzip2

RUN apt-get install -y wget

RUN echo "mysql-server-5.5 mysql-server/root_password_again password cococode123" | debconf-set-selections && \
echo "mysql-server-5.5 mysql-server/root_password password cococode123" | debconf-set-selections && \
apt-get install -y mysql-server

RUN wget -O - http://elkarbackup.org/apt/archive.gpg.key | apt-key add -
RUN echo "deb http://elkarbackup.org/apt/debian jessie main" | tee -a /etc/apt/sources.list

RUN apt-get update

RUN mysqld & \
echo "elkarbackup elkarbackup/dbadminname text root" | debconf-set-selections && \
echo "elkarbackup elkarbackup/dbadminpassword password cococode123" | debconf-set-selections && \
echo "elkarbackup elkarbackup/dbhost text 127.0.0.1" | debconf-set-selections && \
echo "elkarbackup elkarbackup/dbuserpassword password cococode123" | debconf-set-selections && \
apt-get install -y elkarbackup

CMD /usr/sbin/mysqld & /usr/sbin/apache2ctl -D FOREGROUND
```
But this is not the way i want to work ! I have put mysql inside the same container !

**Comment by xezpeleta** [comment]
You did a great job :)

If I run "dpkg-reconfigure elkarbackup" on the container, it works. So apparently there is any problem related to the unattended elkarbackup installation on the postinst step.

I'll check that!

**Comment by xezpeleta** [comment]
Hi @benjaminderei 

Apparently the `setfacl` commands executed by the elkarbackup deb package don't work well when we do the `docker build`. Probably the filesystem used by Docker doesn't support ACLs.

The good news is that if we change the permissions on the run stage it works! So, I modified your code and added an entrypoint script:

__Dockerfile__

```yaml
FROM debian:jessie

RUN apt-get update
RUN apt-get install -y debconf php5 php5-cli rsnapshot php5-mysql acl bzip2

RUN apt-get install -y wget

RUN echo "mysql-server-5.5 mysql-server/root_password_again password cococode123" | debconf-set-selections && \
echo "mysql-server-5.5 mysql-server/root_password password cococode123" | debconf-set-selections && \
apt-get install -y mysql-server

RUN wget -O - http://elkarbackup.org/apt/archive.gpg.key | apt-key add -
RUN echo "deb http://elkarbackup.org/apt/debian jessie main" | tee -a /etc/apt/sources.list

RUN apt-get update

RUN mysqld & \
echo "elkarbackup elkarbackup/dbadminname text root" | debconf-set-selections && \
echo "elkarbackup elkarbackup/dbadminpassword password cococode123" | debconf-set-selections && \
echo "elkarbackup elkarbackup/dbhost text 127.0.0.1" | debconf-set-selections && \
echo "elkarbackup elkarbackup/dbuserpassword password cococode123" | debconf-set-selections && \
apt-get install -y elkarbackup

COPY ./entrypoint.sh /
ENTRYPOINT ["/entrypoint.sh"]
```

__entrypoint.sh__

```sh
#!/bin/sh

setfacl  -R -m u:www-data:rwx -m u:elkarbackup:rwx /var/cache/elkarbackup 2>/dev/null
setfacl -dR -m u:www-data:rwx -m u:elkarbackup:rwx /var/cache/elkarbackup 2>/dev/null
setfacl  -R -m u:www-data:rwx -m u:elkarbackup:rwx /var/log/elkarbackup 2>/dev/null
setfacl -dR -m u:www-data:rwx -m u:elkarbackup:rwx /var/log/elkarbackup 2>/dev/null

/usr/sbin/mysqld & /usr/sbin/apache2ctl -D FOREGROUND
```

Do not forget to add the execution bit to the entrypoint script. And yes, agree with you, now we should put the mysql process in another container.

**Comment by benjaminderei** [comment]
Thx ! :)

Do you think you can: 
- add an option to debian install for killing the mysqldb user and db creation in post-script?
- separate the mysql thinks in another script ?
This way we can add an option for apt-get install in Dockerfile and execute the mysql things script in the first docker run after building !

Ben.

**Comment by benjaminderei** [comment]
Mmmmm' i think we also forget to launch cron daemon :) and we have to redirect all log to stdout !

**Comment by xezpeleta** [comment]
Probably the best option with Docker would be to install ElkarBackup using the tarball instead of Debian package. This way we could use it with any base system (Debian, Centos, Alpine...), choose the latest or custom ElkarBackup version and attach it to any database (MySQL, MariaDB, etc).

So, first of all, I'll try to create an installer valid for any Linux distribution. I'll keep you updated.

**Comment by xezpeleta** [comment]
Hi @benjaminderei ,

I've generated some Elkarbackup docker images. Take a look: https://hub.docker.com/r/elkarbackup/elkarbackup/
