### ISSUE TITLE
PHP Fatal error: Uncaught Error: class 'DOMDocument' not found

### ISSUE THREAD

**Issue by xezpeleta** [elkarbackup/elkarbackup#266]
```
PHP Fatal error:  Uncaught Error: Class 'DOMDocument' not found in /usr/share/elkarbackup/vendor/symfony/symfony/src/Symfony/Component/Config/Util/XmlUtils.php:52
Stack trace:
#0 /usr/share/elkarbackup/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php(284): Symfony\Component\Config\Util\XmlUtils::loadFile('/usr/share/elka...', Array)
#1 /usr/share/elkarbackup/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php(41): Symfony\Component\DependencyInjection\Loader\XmlFileLoader->parseFileToDOM('/usr/share/elka...')
#2 /usr/share/elkarbackup/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php(57): Symfony\Component\DependencyInjection\Loader\XmlFileLoader->load('web.xml')
#3 /usr/share/elkarbackup/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/MergeExtensionConfigurationPass.php(55): Symfony\Bundle\FrameworkBundle\DependencyInjection\FrameworkExtension->load(Array, Object(Symfony\C in /usr/share/elkarbackup/vendor/symfony/symfony/src/Symfony/Component/Config/Util/XmlUtils.php on line 52
```

**Comment by xezpeleta** [comment]
Solved installing php xml:

```
apt install php-xml
/usr/share/elkarbackup/app/console c:c --env=prod
```

We should add php-xml to dependencies
