### ISSUE TITLE
Error adding backup location in 1.3

### ISSUE THREAD

**Issue by gpulido** [elkarbackup/elkarbackup#319]
I have installed the v1.3.0-apache docker image.
After trying to add a new backup location when saving I receive the following error:
```
Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException: You have requested a non-existent parameter "eb.secret". Did you mean this: "secret"? in /app/elkarbackup/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php:84 Stack trace: #0 /app/elkarbackup/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php(200): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->get('eb.secret') #1 /app/elkarbackup/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php(171): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->resolveString('%eb.secret%', Array) #2 /app/elkarbackup/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php(200): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->resolveValue('%eb.secret%', Array) #3 /app/elkarbackup/vendor/symfony/symfony/src/Symfony/Component/DependencyI in /app/elkarbackup/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php on line 84
```
However after going back to the manage locations list, the location is created anyway.

**Comment by xezpeleta** [comment]
Please, report docker related issues in [elkarbackup-docker](https://github.com/elkarbackup/elkarbackup-docker) repository
